### ISSUE TITLE
rgb_strip init failed: ws2811_init failed with code -3 (Hardware revision is not supported)

### ISSUE THREAD

**Issue by Sulpirid** [sunfounder/pironman#19]
Hi, I have multiple issues while running pironman on RPI 5 model B rev. 1.0. See attached screens of terminal.
<img width="832" alt="Screenshot 2024-12-29 at 16 09 36" src="https://github.com/user-attachments/assets/da58932a-7d9e-43da-b744-474f8551d2aa" />
<img width="788" alt="Screenshot 2024-12-29 at 16 11 46" src="https://github.com/user-attachments/assets/9fb001b3-c925-460f-b80f-d52edff75052" />

When I bypassed the rgb_strip init it gives me Cannot determine SOC peripheral base address. Plus the OLED is all messed up. I dont know if I should revert to another library like lgpio or gpiozero. 
![IMG_1794](https://github.com/user-attachments/assets/a65af982-a28d-401a-adde-f18c22ff3549)

**Comment by Lovmong** [comment]
Just in case you might not be clear, for pironman5 you should use the code from the pironman5 repository： https://github.com/sunfounder/pironman5
https://docs.sunfounder.com/projects/pironman5/en/latest/set_up/set_up_rpi_os.html
