### ISSUE TITLE
No pironman on Ubuntu

### ISSUE THREAD

**Issue by twork** [sunfounder/pironman#7]
My new Pironman works fine, as expected, on the "stock" Raspberry Pi OS.

I like to use the Pi with Debian, or Ubuntu, so I'm currently running the latest version of Ubuntu available from the RPi download service.  If I boot the same hardware through the same process listed at: 

  https://docs.sunfounder.com/projects/pironman/en/latest/setup_pironman.html

...when I reach the stage: 

`sudo python3 install.py`

...I get three error messages:

``` - update pip3... Error```

...and:

```
 - install rpi-ws281x... Error
 - install pillow --no-cache-dir... Error
 ```

I've verified that pip3 is installed, so I don't know what that "Error" message refers to, and I'm clueless around the other two problems.

I find that the software was installed under '/opt/pironman'.  Under '/opt/pironman/' I find a file, "log" (marked in executable state, which is not good, but that's a different issue; moving along...); under that file I find:

```
Traceback (most recent call last):
  File "/opt/pironman/main.py", line 12, in <module>
    from ws2812_RGB import WS2812, RGB_styles
  File "/opt/pironman/ws2812_RGB.py", line 3, in <module>
    from rpi_ws281x import PixelStrip, Color # https://github.com/jgarff/rpi_ws281x
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'rpi_ws281x'
Traceback (most recent call last):
  File "/opt/pironman/main.py", line 12, in <module>
    from ws2812_RGB import WS2812, RGB_styles
  File "/opt/pironman/ws2812_RGB.py", line 3, in <module>
    from rpi_ws281x import PixelStrip, Color # https://github.com/jgarff/rpi_ws281x
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'rpi_ws281x'

```

Is this a known issue?  For example, do I need to run Ubuntu under an older version, maybe?

Thanks.

**Comment by Lovmong** [comment]
Ubuntu 23.0 added PEP668 restrictions, which caused pip3 to fail to install normally, and this problem was solved in pironman 2.1.0 version. At present, pironman has passed the test in both Ubuntu 23.0 Desktop and Ubuntu 23.0 Server.
